language: rust
cache: cargo
dist: focal

# this matrix generates jobs for the `test` stage
os:
  - linux
  - windows
rust:
  - nightly
  - beta
  - stable
  - 1.35.0
script: cargo test

# run only one comprehensive job first to see if it fails
# then run the rest of the build matrix with simple tests
jobs:
  include:
    - stage: fast-test
      os: linux
      rust: stable
      before_install: ./scripts/install
      script: ./scripts/check
      after_success: |
        cargo tarpaulin --out xml
        bash <(curl -s https://codecov.io/bash)
  exclude:
    - stage: test
      os: linux
      rust: stable
  allow_failures:
    - rust: nightly

stages:
  - fast-test
  - test
