sudo: false
language: rust
cache: cargo
rust:
  - nightly
  - beta
  - stable
  - 1.35.0
script: |
  cargo build &&
  cargo build --all-features &&
  cargo test &&
  cargo test --all-features &&
  cargo doc
